name: lofelt
description: Unlock the Power of Haptics in Mobile Devices on Flutter
version: 0.0.3
homepage: https://github.com/jgrandchavin/lofelt
repository: https://github.com/jgrandchavin/lofelt

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.juliengrandchavin.lofelt
        pluginClass: LofeltPlugin
      ios:
        pluginClass: LofeltPlugin
